config/routes.rb
Rails.application.routes.draw do
  #Aplikācijas sesijas ceļi
  post "/session", to: "session#create"
  delete "/session", to: "session#destroy"

  #Lietotāja daļas ceļi
  get ":password/aktivizet", to: "session#first_login", as: "aktivizet"
  get ":password/atjaunot", to: "session#password_reset", as: "atjaunot"

  get "/profils", to: "users#profile"
  post "lietotajs/:id/atjaunot_paroli", to: "users#password_update"
  resources :users, path: :lietotajs do
    member do
      post "unit_update"
      post "password_update"
      post "send_password_reset"
      post "resignation"
      post "empower_user"
      post "depower_user"
    end
    collection do
      post "promise"
      get "solijuma_registracija", to: "users#bulk_promise"
    end
  end

  #Aptaujas lapas ceļi. Neizmantojam resources, jo aptaujas lapa ir piesaistīta katram lietotājam
  get "/aptaujas_lapa", to: "personal_information#show"
  delete "/aptaujas_lapa", to: "personal_information#destroy"
  get "/aptaujas_lapa/iesniegt", to: "personal_information#new"
  post "/aptaujas_lapa/iesniegt", to: "personal_information#create"
  patch "/aptaujas_lapa/iesniegt", to: "personal_information#update"
  get "/aptaujas_lapa/labot", to: "personal_information#edit"
  get "/aptaujas_lapa/skatit", to: "personal_information#display"

  #Vienības darbības sfēras ceļi
  resources :units, path: :vieniba do
    member do
      patch "undestory"
    end
  end
  resources :positions, only: ["create", "destroy"]
  resources :weekly_activities, only: ["create", "destroy"]
  resources :membership_fee_payments, path: :biedra_naudas_maksajumi, only: ["create", "destroy"] do
    member do
      get "maksajumi", to: "membership_fee_payments#list"
    end
    collection do
      get "registret_maksajumus", to: "membership_fee_payments#bulk_payment"
      get "maksajumu_vesture", to: "membership_fee_payments#user_payment_history"
    end
  end

  #Atskaišu ceļi
  get "/biedru_atskaites", to: "reports#member_report"
  get "/vienibas_atskaites", to: "reports#unit_report"

  #Pasākumu ceļi
  resources :events, path: :pasakums do
    member do
      get "show_unit"
    end
  end
  resources :invites, only: ["create", "destroy"]
  resources :event_registrations, only: ["create", "destroy", "show"], path: "pieteikumi"

  #Lapa kurā nav vajadzīga reģistrācija
  root "static#landing"
end

app/models/unit.rb
class Unit < ApplicationRecord
  #Definējam obligātos laukus
  validates :city, :number, :legal_adress, :bank_account, presence: true

  #Objektu saistības
  belongs_to :unit_leader, class_name: "User", optional: true

  has_many :users, foreign_key: 'unit_id'
  has_many :events
  has_many :invites
  has_many :event_invites, through: :invites, source: :event
  has_many :membership_fee_payments
  has_many :positions
  has_many :weekly_activities

  def full_name #Vienības pilnais nosaukums
    if number == 0 
      "LSGCO"
    elsif city.ends_with?("i")
      "#{city.slice(0...-1)}u #{number}. vienība"
    elsif city.ends_with?("ls")
      "#{city} #{number}. vienība"
    elsif city.ends_with?("s")
      "#{city.slice(0...-1)}a #{number}. vienība"
    else
      "#{city}s #{number}. vienība"
    end
  end

  def get_actual_events(user) #Pasākumi, kuriem vienībai ir ielūgumi norādītajai pakāpei
    events = invites.includes(:event).future.where(rank: user.rank).map(&:event).select { |event| event.publishable }

    if(user.volunteer == true)
      volunteer_events = invites.includes(:event).future.where("necessary_volunteers >= registered_volunteers").map(&:event).select { |event| 
      event.publishable && 
      event.volunteer_scope == "Ielūgtās vienības" || 
      event.volunteer_scope == "Vienība" && event.unit == user.unit}

      events.concat(volunteer_events)
    end

    return events
  end

  def unit_active? #Vai vienība ir dzēsta
    !deleted_at.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password #Paroles šifrēšana (bcrypt gem)

  #Definējam obligātos laukus
  validates :name, :surname, :activity_statuss, :membership_fee_bilance, :joined_date, :permission_level, presence: true

  #Definējam iespējamās vērtības
  enum activity_statuss: ["Aktīvs", "Daļēji aktīvs", "Interesents", "Vadītājs", "Vecbiedrs", "Neaktīvs", "Izstājies"]
  enum sex: ["M", "F", "O"]
  enum permission_level: ["pklv_biedrs", "pklv_vaditajs", "pklv_valde"]

  #Objektu saistības
  has_many :rank_histories
  has_one :personal_information, dependent: :destroy
  belongs_to :unit
  has_one :leader_for_unit, foreign_key: "unit_leader_id", class_name: "Unit"

  has_many :event_registrations
  has_many :events, through: :event_registrations

  has_many :payed_fees, foreign_key: "user_payed_id", class_name: "MembershipFeePayment"
  has_many :registered_fees, foreign_key: "user_recorded_id", class_name: "MembershipFeePayment"

  has_many :positions

  def years_in_organization #Pilni gadi organizācijā. 365.25 dienas gadā ņemot vērā garos gadus.
    ((Date.today - joined_date) / 365.25).to_i
  end

  def full_name
    "#{name} #{surname}"
  end

  def rank #Pašreiz aktīvā pakāpe
    history = rank_histories.where(current: true).first
    history ? history.rank : "Tev nav norādīta pakāpe"
  end

  def youth? #Vai ir dižskauts vai vecāks
    ["DZSK/DZG", "ROV/LG", "VAD", "VIEDSK/VIEDG"].include?(rank)
  end

  def promise? #Vai pašreizējā pakāpe ir ar solījuma datumu, atgriež datumu
    history = rank_histories.where(current: true).first
    history.present? ? history.date_of_oath : false
  end

  def recalculate_bilance #Pārrēķina bilanci, tiek izsaukta automātiski
    if activity_statuss == "Neaktīvs" || activity_statuss == "Izstājies" #Ja lietotājs nav aktīvs, pārtraucam funkciju
      return nil
    end

    bilance = membership_fee_bilance
    org_fee = Unit.find_by(number: 0).membership_fee
    full_fee = org_fee ? org_fee : 0 #Visiem lietotājiem jāmaksā organizācijas dalības maksa

    if activity_statuss != "Daļēji aktīvs" #Lietotājiem kas ir aktīvi jāmaksā arī vienības dalības maksa
      full_fee += unit.membership_fee ? unit.membership_fee : 0
    end

    #Atjauno bilances datus DB
    new_bilance = bilance - full_fee
    update(membership_fee_bilance: new_bilance)
    reload
  end

  def available_events #Aktuālo pasākumu sarakstss
    events = unit.get_actual_events(self) #Vienības aktuālie pasākumi lietotāja pakāpei

    if volunteer #Ja lietotājs ir brīvprātīgais pievieno visus pasākumus kam vajadzīgi brīvprātīgie
      global_events = Event.future.select { |event| event.publishable && event.volunteer_scope == "Organizācija"}
      events.concat(global_events)
    end

    events.each do |event| #Sarakstā atzīmējam uz kuriem pasākumiem lietotājs ir reģistrējies
      event.registered = event_registrations.exists?(event: event)
    end

    return events.uniq #Atgriežam tikai unikālos ierakstus
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #Pārbauda vai lietotājs ir autorizējies un vai tam ir pieteikamas piekļuves
  before_action :authorized?
  before_action :unit_access?, only: ["create", "new", "unit_update", "show", "promise", "empower_user", "depower_user"]
  before_action :org_access?, only: ["index"]   #Tikai var apskatīties sarakstu ar visiem lietotājiem
  before_action :unit_active?, only: ["create"]   #Veidojam jaunu lietotāju tikai aktīvām vienībām

  def new #Tukšs lietotāja objekts ar ko aizpildīt jauna lietotāja formu
    session[:current_tab] = "new_member"  #Iestatam, ka izvēlnes aktīvā sekcija ir jauna lietotāja pievienošana
    @units = Unit.where(deleted_at: nil).map {|unit| [unit.full_name, unit.id]}
    @user = User.new
  end

  def index #Visi sistēmas lietotāji
    session[:current_tab] = "user_list"  #Iestatam, ka izvēlnes aktīvā sekcija ir biedru saraksts
    @users = User.all
  end

  def create #Izveido jaunu lietotāju
    @user = User.new(user_params.except(:rank, :unit)) #Aizpildam ar vērtībām izņemot rank un unit, ko izmanto zemāk, lietotāja vienība sakrīt ar tā veidotāja vienību ja nav admin
    @user.unit = user_params[:unit].present? ? Unit.find(user_params[:unit]) : current_user.unit 
    password = rand(36**20).to_s(36)  #Pagaidu randomizēta parole
    @user.password_digest = BCrypt::Password.create(password).to_s #Šifrēšana

    @rank = RankHistory.new(user: @user, date_begin: Date.today, rank: user_params[:rank], current: true) #Lietotāja pakāpes vēsture

    @user.username = user_params[:name].capitalize + user_params[:surname].capitalize + current_user.unit.number.to_s #Lietotāja lietotājvārda izveide (piem. VārdsUzvārds29)
    if @user.save && @rank.save #Ja kļūda saglabājot lietotāju un pakāpi, paziņo
      #Saite uz paroles atiestatīšanu, epasta nosūtīšana
      link = aktivizet_path(id: @user.id, password:) 
      UserMailer.first_login_email(current_user, @user, link).deliver_later
      redirect_to root_path, notice: 'Biedrs pievienots'
    else
      redirect_to root_path, alert: 'Kļūda'
    end
  end

  def edit #Lietotāja objekts ar ko aizpildīt lietotāja datu atjaunošanas formu
    @user = User.find(params[:id])
    @new_user = session[:new_user]
  end

  def show #Lietotāja dati vienības priekšnieka apskatei
    @user = User.find(params[:id])
    @avalable_ranks = RankHistory.ranks.filter{|rank| !@user.rank_histories.where(rank: rank, current: false).present?}.keys #Pakāpes, kurās lietotājs nav bijis
    @units = Unit.where(deleted_at: nil).map {|unit| [unit.full_name, unit.id]} #Organizācijas vienību saraksts
    @new_position = Position.new() #Tukšs jauna amata objekts
  end

  def update #atjauno lietotāju, ja neizdodas saglabāt Paziņo kļūdu.
    @user = User.find(params[:id])

    if @user.update(user_update_params)
      redirect_to root_path, notice: 'Dati atjaunoti'
    else
      redirect_to root_path, alert: 'Kļūda'
    end
  end

  def destroy #Nestingrā dzēšana lietotājam, ja neizdodas nomainīt statusu Paziņo kļūdu
    @user = User.find(params[:id])
    @unit = @user.unit

    if @user.update(activity_statuss: "Izstājies")
      redirect_to unit_path(@unit), notice: 'Profils dzēsts'
    else
      redirect_to unit_path(@unit), alert: 'Kļūda'
    end

  end

  def profile #Lietotāja dati lietotāja apskatei
    session[:current_tab] = "profile"  #Iestatam, ka izvēlnes aktīvā sekcija ir profils
    @new_user = session[:new_user]
    @user = current_user
    @events = @user.available_events.sort_by(&:date_from) #Lietotāja aktuālie pasākumi

  end

  def unit_update #Lietotāja atjaunošana, ko veic vienības priekšnieks
    @user = User.find(params[:id])

    if user_unit_edit_params[:unit_id] #Maina vienību, ja tāda norādīta, Paziņo ja kļūda
      @user.unit = Unit.find(user_unit_edit_params[:unit_id])
      if @user.save!
        redirect_to user_path(@user), notice: 'Vienība nomainīta'
      else
        redirect_to user_path(@user), alert: 'Kļūda'
      end
    end

    if user_unit_edit_params[:activity_statuss] #Maina aktivitātes statusu, ja tas norādīts, Paziņo ja kļūda
      @user.activity_statuss = user_unit_edit_params[:activity_statuss]
      if @user.save!
        redirect_to user_path(@user), notice: 'Aktivitātes statuss nomainīts'
      else
        redirect_to user_path(@user), alert: 'Kļūda'
      end
    end

    if user_unit_edit_params[:rank] #Mainam pakāpi ja tā norādita, Paziņo ja kļūda
    @rank = RankHistory.new(user: @user, date_begin: Date.today, rank: user_unit_edit_params[:rank], current: true) #Izveidojam jaunu pašreizējo pakāpes vēstures objektu.

    if @user.rank_histories.where(current: true).update(current: false) && @rank.save! #Vecajai pakāpes vēsturei noņemam pašreizējās statusu un saglabājam jauno, Paziņo
      redirect_to user_path(@user), notice: 'Pakāpe nomainīta'
    else
      redirect_to user_path(@user), alert: 'Kļūda'
    end
    end
  end

  def promise
    date = params[:promise_date]
  
    if params[:user_ids].present?
      users = params[:user_ids]
      results = []
      users.each do |user|
        user_record = User.find(user)
        results.push(register_promise(user_record, date))
      end

      if results.include?(false)
        redirect_to solijuma_registracija_users_path(), alert: 'Kļūda'
      else
        redirect_to solijuma_registracija_users_path(), notice: 'Solījums atzīmēts'
      end
    elsif params[:id].present?
      user_record = User.find(params[:id])
      if register_promise(user_record, date)
        redirect_to user_path(user), notice: 'Solījums atzīmēts'
      else
        redirect_to user_path(user), alert: 'Kļūda'
      end
    end
  end
  

  def password_update #Lietotāja paroles atiestatīšana
    @user = User.find(params[:id])
    #Atkarībā no tā vai lietotājs ir jauns atšķiras saite uz ko pārvirzīt to un ar kādu paziņojumu
    path = session[:new_user] == true || session[:password_reset] == true ? aktivizet_path(@user.id, params[:old_password]) : edit_user_path(@user.id)
    success_notice = session[:new_user] == true ? "Parole izveidota" : "Parole atjaunota"

    if params[:password_digest] != params[:repeat_password] #Pārbaude vai 2x ievadītā parole sakrīt, ja nē pārvirzam ar paziņojumu
      redirect_to path, notice: 'Paroles nesakrīt'
      return
    end

    if @user.authenticate(params[:old_password]) #Ja vecās paroles parametrs sakrīt ar lietotāja paroli šifrējam jauno paroli un atjauno.
      @user.password_digest = BCrypt::Password.create(params[:password_digest]).to_s
    else #Citādi Paziņo. Jauns lietotājs tiek pārvirzīts uz sākuma skatu, reģistrējies uz lietotāja datu atjaunošanu
      if session[:new_user] == true
      session.clear
      redirect_to root_path, notice: 'Nepareiza parole'
      else
      redirect_to edit_user_path(current_user), notice: 'Nepareiza pašreizējā parole'
      end
      return
    end

    if @user.save #Saglabājam jauno paroli un Paziņo
      redirect_to edit_user_path(current_user), notice: success_notice
    else
      redirect_to path, alert: 'Kļūda'
    end
  end

  def send_password_reset #Paroles atiestatīšanas epasta nosūtīšana lietotājam
    @user = User.find(params[:id])
    #atjauno lietotāja paroli uz pagaidu randomizētu paroli
    password = rand(36**20).to_s(36)
    @user.password_digest = BCrypt::Password.create(password).to_s
    @user.save!

    @link = atjaunot_path(id: @user.id, password:) #Saite uz paroles atiestatīšanas skatu

    #Nosūtam epastu un Paziņo par to
    UserMailer.password_reset_email(@user, @link).deliver_later 
    redirect_to user_path(@user), notice: "Epasts ar paroles atjaunošanas instrukcijām nosūtīts"
  end

  def resignation #Lietotāja izstāšanās iesniegums
    @user = @current_user

    @link = user_path(@user.id) #Links uz lietotāja biedra paneli

    if @user.update(activity_statuss: "Neaktīvs")
      #Ja izdodas atjaunot statusu dzēšam aptaujas lapu ja tāda ir un nosūtam epastu vienības priekšniekam.
      if @user.personal_information.present?
        @user.personal_information.destroy
      end
      UserMailer.user_resignation_email(@user, @user.unit.unit_leader, @link).deliver_later
      redirect_to edit_user_path(current_user), notice: "Jūsu iesniegums ir nosūtīts"
    else
      redirect_to edit_user_path(current_user), alert: 'Kļūda'
    end
  end

  def empower_user
    permission_level = params[:permission]
    @user = User.find(params[:id])
    
    if @user.youth? && permission_level == "pklv_vaditajs" && @current_user.leader_for_unit || permission_level == "pklv_valde" && @current_user.permission_level == "pklv_valde"
      if @user.update(permission_level: permission_level)
        redirect_to user_path(params[:id]), notice: 'Piekļuve piešķirta'
      else
        redirect_to user_path(params[:id]), alert: 'Kļūda'
      end
    else
      redirect_to user_path(params[:id]), alert: 'Trūkst piekļuves'
    end
  end

  def depower_user
    @user = User.find(params[:id])
    permission = "pklv_biedrs"

    if @user.leader_for_unit
      permission = "pklv_vaditajs"
    end

    if @user.update(permission_level: permission)
      redirect_to user_path(params[:id]), alert: 'Piekļuve samazināta'
    else
      redirect_to user_path(params[:id]), alert: 'Kļūda'
    end
  end

  def bulk_promise
    @users = User.joins(:rank_histories).where(unit: current_user.unit, rank_histories: {current: true, date_of_oath: nil}).order(name: :asc)
  end

  protected

   #Pieņem lietotāja objektu, kas aizpildīts atļautajiem laukiem. Šo izmanto veicot vienības priekšnieka darbības ar lietotāju.
  def user_unit_edit_params
    params.permit(:activity_statuss, :unit_id, :rank)
  end

   #Pieņem lietotāja objektu, kas aizpildīts atļautajiem laukiem. Šo izmanto atjaunojot lietotāju.
  def user_update_params
    params.require(:user).permit(:name, :surname, :phone, :email, :birth_date, :sex, :agreed_to_photos, :agreed_to_data_collection, :volunteer)
  end

app/views/users/_bilance-data.html.slim
.flex.flex-col.items-center.gap-2
  -if @user.membership_fee_bilance >= 0
    h1.main-title.text-green-800
      =@user.membership_fee_bilance.to_s + "€"
  -else
    h1.main-title.text-red-800
      =@user.membership_fee_bilance.to_s + "€"  
  p.text-lg.text-center.mt-2
    |Lai nomaksātu biedra naudu, lūdzu pārskaitīt naudu uz savas vienības kontu: 
  b
    =@user.unit.bank_account 
    

app/views/users/_bilance_data.html.slim
.flex.flex-col.items-center.gap-2
  div.flex.gap-2
    -if @user.membership_fee_bilance >= 0
      h1.main-title.text-green-800
        =@user.membership_fee_bilance.to_s + "€"
    -else
      h1.main-title.text-red-800
        =@user.membership_fee_bilance.to_s + "€"  
  p.text-lg.text-center.mt-2
    |Lai nomaksātu biedra naudu, aicinām to pārskaitīt uz savas vienības kontu:
  b 
    |Latvijas skautu un gaidu centrālā organizācija:
  b
    =@user.unit.bank_account 
    

app/views/users/_bulk_promise_form.html.slim
script src = javascript_path("multiselect")

link rel="stylesheet" href=stylesheet_path("multiselect_override")

=form_tag promise_users_path() do 
  .
    div 
      = select_tag :user_ids, options_for_select(@users.map {|user| [user.full_name, user.id]}), multiple: true, id: "multiSelect", class: "input-field-blue w-full h-full"
    label for="user_ids" class="input-label-static"
      |Solījumu deva
  button type="submit" class="btn-primary"
    |Reģistrēt solījumus
    

app/views/users/_permission_button.slim
-if @user.pklv_biedrs? && (@current_user.pklv_vaditajs? || @current_user.pklv_valde?) && @current_user.leader_for_unit.present?
  =link_to "Pilnvarot", empower_user_user_path(@user, {permission: "pklv_vaditajs"}), data: { turbo_method: "post" }, class: "btn-primary w-full flex items-center lg:w-2/5", onclick: "return showAlert()"

-if( @user.pklv_biedrs? || @user.pklv_vaditajs?) && @current_user.pklv_valde?
  =link_to "Pievienot valdei", empower_user_user_path(@user, {permission: "pklv_valde"}), data: { turbo_method: "post" }, class: "btn-primary w-full flex items-center lg:w-2/5", onclick: "return showAlert()"

-if (@user.pklv_valde? && @current_user.pklv_valde? ) || (@user.pklv_vaditajs? && @current_user.leader_for_unit.present?)
  =link_to "Dzēst pilnvaras", depower_user_user_path(@user), data: { turbo_method: "post" }, class: "btn-primary w-full flex items-center lg:w-2/5", onclick: "return showAlert()"

app/views/users/_user-data.html.slim
div.flex.flex-col.gap-4
  div.flex.gap-2 
    h1.subtitle 
      |Vārds: 
    p.paragraph-normal 
      =@user.name
  div.flex.gap-2   
    h1.subtitle 
      |Uzvārds: 
    p.paragraph-normal 
      =@user.surname
  div.flex.gap-2   
    h1.subtitle 
      |Vienība: 
    p.paragraph-normal 
      =@user.unit.full_name
  div.flex.gap-2   
    h1.subtitle 
      |Pakāpe: 
    p.paragraph-normal 
      | #{@user.rank} #{ @user.promise? ? (@user.sex == "F" ? "☘️" : "⚜️") : "" }
  - if @user.promise?
    div.flex.gap-2   
      h1.subtitle 
        |Solījuma datums: 
      p.paragraph-normal 
        = @user.promise?
  div.flex.gap-2   
    h1.subtitle 
      |Epasts: 
    p.paragraph-normal 
      =@user.email
  div.flex.gap-2   
    h1.subtitle 
      |Telefons: 
    p.paragraph-normal 
      =@user.phone
  -if @user.positions.present?
    .flex.gap-2 
      h1.subtitle 
        |Amati vienībā:
      p.paragraph-normal 
        =@user.positions.map(&:position_name).join(', ')


    

app/views/users/_user_data.html.slim
div.flex.flex-col.gap-4
  div.flex.gap-2 
    h1.subtitle 
      |Vārds: 
    p.paragraph-normal 
      =@user.name
  div.flex.gap-2   
    h1.subtitle 
      |Uzvārds: 
    p.paragraph-normal 
      =@user.surname
  div.flex.gap-2   
    h1.subtitle 
      |Vienība: 
    p.paragraph-normal 
      =@user.unit.full_name
  div.flex.gap-2   
    h1.subtitle 
      |Pakāpe: 
    p.paragraph-normal 
      | #{@user.rank} #{ @user.promise? ? (@user.sex == "F" ? "☘️" : "⚜️") : "" }
  - if @user.promise?
    div.flex.gap-2   
      h1.subtitle.text-start 
        |Solījuma datums: 
      p.paragraph-normal.text-start 
        = @user.promise?
  div.flex.gap-2   
    h1.subtitle 
      |Epasts: 
    p.paragraph-normal 
      =@user.email.present? ? @user.email :  "-"
  div.flex.gap-2   
    h1.subtitle 
      |Telefons: 
    p.paragraph-normal 
      =@user.phone.present? ? @user.phone : "-"
  -if @user.positions.present?
    .flex.gap-2 
      h1.subtitle 
        |Amati vienībā:
      p.paragraph-normal 
        =@user.positions.map(&:position_name).join(', ')


    

app/views/users/bulk_promise.html.slim
.flex.flex-col.justify-start.p-5.w-full.lg:w-4/5.lg:h-full.lg:p-10
  .flex.flex-col.w-full.h-full.lg:flex-row
    .flex.flex-col.lg:w-3/4
      h1.title-normal
        |Reģistrēt solījumu
      div 
        =render "bulk_promise_form"

      =button_tag "< Atgriezties", onClick: "history.go(-1);", class: "btn-primary w-fit", class: "btn-primary w-fit mt-10 lg:mt-0"

app/views/users/show.html.slim
flex.flex-col.flex-1.justify-start.p-5.lg:h-full.lg:p-10
  .flex.flex-col.w-full.h-full.lg:flex-row
    .flex.flex-col.lg:w-3/5
      h1.title-normal
        |Biedrs
      .border-2.rounded-xl.h-full.p-5.w-full.text-end
        =render partial: "user_data", locals: {user: @user}
    .flex.flex-col.mt-10.lg:w-2/5.lg:ml-10.lg:mt-0
      h1.title-normal
        |Vienību priekšnieka darbības
      .border-2.rounded-xl.p-5
        = form_tag unit_update_user_path(@user), class: "flex flex-col items-center mb-5 place-content-between lg:mb-0 lg:flex-row form-with-alert"
          = select_tag :rank, options_for_select(@avalable_ranks, @user.rank), class: "input-field-blue w-full lg:w-1/2 "
          button.btn-primary.w-full.lg:w-2/5 type="submit"
            |Mainīt pakāpi
        = form_tag promise_users_path(@user), class: "flex flex-col items-center mb-5 place-content-between lg:mb-0 lg:flex-row form-with-alert"
          input type="date" class="input-field-blue w-full lg:w-1/2 " name="promise_date" value=(@user.promise? ? @user.promise? : Date.today)
          input type="hidden" name="id" value=(@user.id)
          button.btn-primary.w-full.lg:w-2/5.disabled:bg-scout-gray type="submit" disabled= @user.promise?
            = @user.promise? ? "Solījums veikts" : "Reģistrēt solījumu"
        = form_tag unit_update_user_path(@user), class: "flex flex-col items-center mb-5 place-content-between lg:mb-0 lg:flex-row"
          = select_tag :activity_statuss, options_for_select(["Aktīvs", "Daļēji aktīvs", "Interesents", "Vadītājs", "Vecbiedrs", "Neaktīvs"], @user.activity_statuss), class: "input-field-blue w-full lg:w-1/2 "
          button.btn-primary.w-full.lg:w-2/5 type="submit"
            |Mainīt statusu
        = form_tag unit_update_user_path(@user), class: "flex flex-col items-center mb-5 place-content-between lg:mb-0 lg:flex-row form-with-alert"
          = select_tag :unit_id, options_for_select(@units, @user.unit.id), class: "input-field-blue w-full lg:w-1/2 "
          button.btn-primary.w-full.lg:w-2/5 type="submit"
            |Mainīt vienību
        br
        = form_for @new_position do |f|
          h1.title-normal.text-lg.ml-2
            |Biedra amati vienībā
          .flex.items-center.place-content-between.flex-col.lg:flex-row
            = f.text_field :position_name, required: true, class: "input-field-blue w-full lg:w-1/2 "
            = f.hidden_field :user_id, value: @user.id
            = f.submit "Pievienot amatu", class: "btn-secondary w-full lg:w-2/5"
        -@user.positions.each do |position|
          .flex.items-center.place-content-between
            h1
              =position.position_name
            h1 
              |No #{position.created_at.strftime("%d/%m/%Y")}
            =button_to "#{agent_mobile? ? "X" : "Dzēst"}", position_path(position), method: :delete, class: "btn-secondary border-scout-red text-scout-red text-sm min-h-[18px] lg:text-lg"

        .flex.items-end.mt-5.flex-col
          =link_to "Atiestatīt paroli", send_password_reset_user_path(@user), data: { turbo_method: "post" }, class: "btn-primary w-full flex items-center lg:w-2/5", onclick: "return showAlert()"
          -if @user != @current_user && @user.activity_statuss == "Neaktīvs"
            =link_to "Dzēst biedru", user_path(@user), data: { turbo_method: "delete" }, class: "btn-primary bg-scout-red w-full flex items-center lg:w-2/5", onclick: "return showAlert()"

          -if @user.youth?
            = render partial: "permission_button", locals: {user: @user}
        
  .mt-10.flex.flex-col
    =link_to maksajumi_membership_fee_payment_path(@user), class: "btn-primary flex items-center lg:w-1/5 items-center justify-between"
      | #{@user.name} Maksājumi
      =image_tag 'icons/money.svg', size:"30"
    =button_tag "< Atgriezties", onClick: "history.go(-1);", class: "btn-primary w-fit"