config/routes.rb
Rails.application.routes.draw do
  #Aplikācijas sesijas ceļi
  post "/session", to: "session#create"
  delete "/session", to: "session#destroy"

  #Lietotāja daļas ceļi
  get ":password/aktivizet", to: "session#first_login", as: "aktivizet"
  get ":password/atjaunot", to: "session#password_reset", as: "atjaunot"

  get "/profils", to: "users#profile"
  post "lietotajs/:id/atjaunot_paroli", to: "users#password_update"
  resources :users, path: :lietotajs do
    member do
      post "unit_update"
      post "password_update"
      post "send_password_reset"
      post "resignation"
      post "empower_user"
      post "depower_user"
    end
    collection do
      post "promise"
      get "solijuma_registracija", to: "users#bulk_promise"
    end
  end

  #Aptaujas lapas ceļi. Neizmantojam resources, jo aptaujas lapa ir piesaistīta katram lietotājam
  get "/aptaujas_lapa", to: "personal_information#show"
  delete "/aptaujas_lapa", to: "personal_information#destroy"
  get "/aptaujas_lapa/iesniegt", to: "personal_information#new"
  post "/aptaujas_lapa/iesniegt", to: "personal_information#create"
  patch "/aptaujas_lapa/iesniegt", to: "personal_information#update"
  get "/aptaujas_lapa/labot", to: "personal_information#edit"
  get "/aptaujas_lapa/skatit", to: "personal_information#display"

  #Vienības darbības sfēras ceļi
  resources :units, path: :vieniba do
    member do
      patch "undestory"
    end
  end
  resources :positions, only: ["create", "destroy"]
  resources :weekly_activities, only: ["create", "destroy"]
  resources :membership_fee_payments, path: :biedra_naudas_maksajumi, only: ["create", "destroy"] do
    member do
      get "maksajumi", to: "membership_fee_payments#list"
    end
    collection do
      get "registret_maksajumus", to: "membership_fee_payments#bulk_payment"
      get "maksajumu_vesture", to: "membership_fee_payments#user_payment_history"
    end
  end

  #Atskaišu ceļi
  get "/biedru_atskaites", to: "reports#member_report"
  get "/vienibas_atskaites", to: "reports#unit_report"

  #Pasākumu ceļi
  resources :events, path: :pasakums do
    member do
      get "show_unit"
    end
  end
  resources :invites, only: ["create", "destroy"]
  resources :event_registrations, only: ["create", "destroy", "show"], path: "pieteikumi"

  #Lapa kurā nav vajadzīga reģistrācija
  root "static#landing"
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :date_from, :date_to, :event_type, :registration_till, :volunteer_scope, presence: true

  enum event_type: ["Nometne", "Pārgājiens", "Darba grupa", "Labais darbs", "Cits"]
  enum volunteer_scope: ["Vienība", "Ielūgtās vienības", "Organizācija"]

  belongs_to :unit
  has_many :invites
  has_many :invited_units, through: :invites, source: :unit
  has_many :event_registrations
  has_many :users, through: :event_registrations

  #Papildus parametrs lai norādītu vai lietotājs ir reģistrējies pasākumam to uzskaitē
  attr_accessor :registered

  #Nestingrā dzēšana- noklusējumā rādam tikai nedzēstos pasākumus
  default_scope { where(deleted_at: nil) }

  #Nākotnes pasākumi
  scope :future, -> { where("date_from > ?", Date.today) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  #Pārbauda vai lietotājs ir autorizējies
  before_action :authorized?
  #Apskatīt pasākumu var jebkurš, pārējām darbībām jābūt ar vienības piekļuves līmeni vai augstāk
  before_action :unit_access?, except: ["show"]
  #Pasākumu izveidot var tikai aktīva vienība
  before_action :unit_active?, only: ["create"]


  helper RegistrationHelpers

  def index #Vienības pasākumu un pasākumu uz ko vienība ielūgta saraksts
    session[:current_tab] = "events"
    @events = current_user.unit.events
    @invites = current_user.unit.invites.map(&:event).select { |event| event.publishable }.uniq
  end

  def show #Pasākuma dati lietotājam
    @event = Event.find(params[:id])
    @event_registration = EventRegistration.new
  end

  def show_unit #Pasākuma dati vienībām
    @event = Event.find(params[:id])
  end

  def new #Tukšs pasākuma objekts ar ko aizpildīt jauna pasākuma formu
    @event = Event.new()
    @units = Unit.where(deleted_at: nil).where.not(number: 0).order(city: :asc) #Organizācijas vienības
  end

  def edit #Pasākuma objekts ar ko aizpildīt pasākuma datu atjaunošanas formu
    @event = Event.find(params[:id])
    @invites = Invite.where(event: @event) #Pasākuma ielūgumi
    @invite = Invite.new()
    @units = Unit.where(deleted_at: nil).where.not(number: 0).map {|unit| [unit.full_name, unit.id]} #Organizācijas vienības priekš izvēles
  end

  def create #Izveido pasākumu pašreizējā lietotāja vienībai un ielūgumus atzīmētajām vienībām un pakāpēm, ja kļūda paziņo
    @unit = current_user.unit
    @event = Event.new(event_params.except(:units, :ranks))
    @event.unit = @unit

    if @event.save! && generate_invites(event_params[:units], event_params[:ranks], @event)
      redirect_to events_path, notice: "Pasākums izveidots"
    else
      redirect_to events_path, alert: "Kļūda"
    end
  end

  def update #Atjauno pasākuma datus, ja neizdodas saglabāt, paziņo
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to events_path, notice: "Pasākums atjaunots"
    else
      redirect_to events_path, alert: "Kļūda"
    end
  end

  def destroy #Nestingri dzēš pasākumu, dzēš ar to saistītos ielūgumus un reģistrācijas, ja neizdodas atjaunot pasākuma dzēšanas laiku, paziņo
    @event = Event.find(params[:id])

    if @event.update(deleted_at: Time.now) && delete_invites(@event) && delete_registrations(@event)
      redirect_to events_path, notice: "Pasākums dzēsts"
    else
      redirect_to events_path, alert: "Kļūda"
    end
  end

  protected

  #Pieņem pasākuma objektu ar atļautajiem laukiem
  def event_params
    params.require(:event).permit(:name, :description, :date_from, :date_to, :event_type, :necessary_volunteers, :max_participants, :deleted_at, :registration_till, :publishable, :volunteer_scope, units: [], ranks: [])
  end

  #Funkcija, kas izveido ielūgumus vienību masīva pakāpēm, kas pakāpju masīvā
  def generate_invites(units, ranks, event)
    return true unless units.present? && ranks.present?
    if units.present? && ranks.present?
      ranks.each do |rank|
        units.each do |unit_id|
          unit = Unit.find(unit_id)
          Invite.create(rank:, unit:, event:)
        end
      end
    end
  end

  #Funkcija, kas dzēš visus ielūgumus no pasākuma
  def delete_invites(event)
    event.invites.each do |invite|
      invite.delete
    end
  end

  #Funkcija, kas dzēš visas reģistrāciajas no pasākuma
  def delete_registrations(event)
    event.event_registrations.each do |registration|
      registration.delete
    end
  end
end

app/views/events/_create_event_form.html.slim
=form_for @event do |f|
  .flex.flex-col.w-full.lg:flex-row 
    .flex.flex-col.lg:w-1/2
      div
        = f.text_field :name, required: true, class: 'input-field-blue w-full peer', placeholder: ""
        = f.label :name, "Nosaukums", class: 'input-label'
      div
        = f.text_area :description, class: 'input-field-blue rounded-[30px] w-full h-60 overflow-auto peer', placeholder: ""
        = f.label :name, "Apraksts", class: 'input-label'   
      .flex.w-full.mt-2
        .flex.flex-col.lg:w-1/2
          = f.select :event_type,  options_for_select(Event.event_types.keys), {}, class: 'input-field-blue w-full'
          = f.label :event_type, "Pasākuma veids", class: 'input-label'
        .flex.flex-col.ml-10.lg:w-1/2
          = f.date_field :registration_till, required: true, value: Date.today + 1, class: 'input-field-blue w-full'
          = f.label :registration_till, "Reģistrēšanās līdz", class: 'input-label'
      .flex.w-full.mt-2
        .flex.flex-col.lg:w-1/2
          = f.date_field :date_from, required: true, value: Date.today + 1, class: 'input-field-blue w-full'
          = f.label :date_from, "No", class: 'input-label'
        .flex.flex-col.ml-10.lg:w-1/2
          = f.date_field :date_to, required: true, value: Date.today + 1, class: 'input-field-blue w-full'
          = f.label :date_to, "Līdz", class: 'input-label', id: 'event_date_to_label'
      .flex.w-full.mt-2
        .flex.flex-col.lg:w-1/2
          = f.number_field :necessary_volunteers, required: true, class: 'input-field-blue w-full'
          = f.label :necessary_volunteers, "Vajadzīgie brīvprātīgie", class: 'input-label-static'
        .flex.flex-col.ml-10.lg:w-1/2
          = f.number_field :max_participants, required: true, class: 'input-field-blue w-full'
          = f.label :max_participants, "Max dalībnieku skaits", class: 'input-label-static'
      .flex.flex-col
        = f.select :volunteer_scope,  options_for_select(Event.volunteer_scopes.keys), {}, class: 'input-field-blue w-full'
        = f.label :volunteer_scope, "Kuriem brīvprātīgajiem rādīt šo pasākumu?", class: 'input-label-static'
      .flex.p-2
        = f.check_box :publishable, class: 'border-2 border-scout-blue rounded-sm'
        = f.label :publishable, "Vai vēlaties lai šis pasākums tiktu rādīts biedriem?", class: 'text-sm font-bold text-scout-blue ml-2'
    .flex.lg:w-1/2.flex-col.mt-10.lg:ml-10.lg:mt-0.items-center
      .w-4/5
        .flex.flex-wrap.border-2.border-scout-blue.p-2.overflow-auto class="lg:h-[100px] max-h-[425px] overflow-auto rounded-[30px] px-5"
          -ranks_short.each do |rank|
            .flex.p-2
              = check_box_tag 'event[ranks][]', rank, false,  class: 'border-2 border-scout-blue rounded-sm'
              = label_tag "rank#{rank}", rank, class: 'text-sm font-bold text-scout-blue ml-2'
        label for="ranks" class="input-label-static"
          |Pasākums paredzēts šīm pakāpēm
      .w-4/5.mt-10
        .flex.flex-col.border-2.border-scout-blue.p-2.overflow-auto class="h-fit max-h-[60vh] overflow-auto rounded-[30px] px-5 pb-5"
          - @units.each do |unit|
              .flex.p-2 
                = check_box_tag 'event[units][]', unit.id, unit == current_user.unit ? true : false, class: 'border-2 border-scout-blue rounded-sm'
                = label_tag "units#{unit.id}", unit.full_name, class: 'text-sm font-bold text-scout-blue ml-2'
        label for="ranks" class="input-label-static" 
          |Ielūgtas šādas vienības

      = f.submit "Izveidot pasākumu", class: 'btn-primary w-4/5 mt-10'

app/views/events/_event-list-item.html.slim
tr.border-y-2.h-16
  td.paragraph-normal
    =event.name 
  td.paragraph-normal
    ="#{event.date_from.strftime("%d.%m")}#{event.date_to ? "-" + event.date_to.strftime("%d.%m") : ""}"
  td.paragraph-normal.text-end 
    =link_to "Apskatīt", root_path, class:"btn-ternary"

app/views/events/_event_form.html.slim
.flex.flex-col.w-full
  =form_for @event do |f|
    .flex.flex-col
      div
        = f.text_field :name, required: true, class: 'input-field-blue w-full peer', placeholder: ""
        = f.label :name, "Nosaukums", class: 'input-label'
      div
        = f.text_area :description, class: 'input-field-blue rounded-[30px] w-full h-60 overflow-auto peer', placeholder: ""
        = f.label :name, "Apraksts", class: 'input-label'   
      .flex.w-full.mt-2
        .flex.flex-col.lg:w-1/2
          = f.select :event_type,  options_for_select(Event.event_types.keys, selected: @event.event_type), {}, class: 'input-field-blue w-full'
          = f.label :event_type, "Pasākuma veids", class: 'input-label'
        .flex.flex-col.ml-10.lg:w-1/2
          = f.date_field :registration_till, required: true, class: 'input-field-blue w-full'
          = f.label :registration_till, "Reģistrēšanās līdz", class: 'input-label'
      .flex.w-full.mt-2
        .flex.flex-col.lg:w-1/2
          = f.date_field :date_from, required: true, class: 'input-field-blue w-full'
          = f.label :date_from, "No", class: 'input-label'
        .flex.flex-col.ml-10.lg:w-1/2
          = f.date_field :date_to, required: true,  class: 'input-field-blue w-full'
          = f.label :date_to, "Līdz", class: 'input-label', id: 'event_date_to_label'
      .flex.w-full.mt-2
        .flex.flex-col.lg:w-1/2
          = f.number_field :necessary_volunteers, required: true, class: 'input-field-blue w-full'
          = f.label :necessary_volunteers, "Vajadzīgie brīvprātīgie", class: 'input-label-static'
        .flex.flex-col.ml-10.lg:w-1/2
          = f.number_field :max_participants, required: true, class: 'input-field-blue w-full'
          = f.label :max_participants, "Max dalībnieku skaits", class: 'input-label-static'
      .flex.flex-col
        = f.select :volunteer_scope,  options_for_select(Event.volunteer_scopes.keys, @event.volunteer_scope), {}, class: 'input-field-blue w-full'
        = f.label :volunteer_scope, "Kuriem brīvprātīgajiem rādīt šo pasākumu?", class: 'input-label-static'
      .flex.p-2
        = f.check_box :publishable, class: 'border-2 border-scout-blue rounded-sm'
        = f.label :publishable, "Vai vēlaties lai šis pasākums tiktu rādīts biedriem?", class: 'text-sm font-bold text-scout-blue ml-2'
    = f.submit "Atjaunot pasākuma datus", class: 'btn-primary w-full mt-11'

app/views/events/_event_list_item.html.slim
tr.border-y-2.h-16 class="#{event.registered ? "text-scout-blue" : "text-black"}"
  td.paragraph-normal
    =event.name 
  td.paragraph-normal
    ="#{event.date_from.strftime("%d.%m")}#{event.date_to ? "-" + event.date_to.strftime("%d.%m") : ""}"
  td.paragraph-normal.text-end 
    =link_to "Apskatīt", event_path(event), class:"btn-ternary"

app/views/events/_event_show.html.slim
  .flex.flex-col.w-full.h-full.lg:w-full.place-content-between
    div  
      h1.title-normal 
        =@event.name
      div.flex.flex-col.gap-1.lg:flex-row.mb-5.w-full
        div.border-2.rounded-3xl.text-center.border-scout-blue.py-1.px-2.w-fit
          p.font-bold
            =@event.event_type
        div.border-2.rounded-3xl.text-center.border-scout-blue.py-1.px-2.w-fit
          p.font-bold
            | No: #{@event.date_from.strftime("%d/%m/%y")}
        div.border-2.rounded-3xl.text-center.border-scout-blue.py-1.px-2.w-fit
          p.font-bold
            | Līdz: #{@event.date_to.strftime("%d/%m/%y")}
        div.border-2.rounded-3xl.text-center.border-scout-blue.py-1.px-2.w-fit
          p.font-bold
            | Rīko: #{@event.unit.full_name}
        -if registration_positions(@event.id).include?("Dalībnieks")
          div.border-2.rounded-3xl.text-center.border-scout-blue.py-1.px-2.w-fit
            p.font-bold
              | Pieteikušies: #{@event.registered_participants} / #{@event.max_participants}
        -if registration_positions(@event.id).include?("Brīvprātīgais") ||  registration_positions(@event.id).include?("Organizators")
          div.border-2.rounded-3xl.text-center.border-scout-blue.py-1.px-2.w-fit
            p.font-bold
              | Brīvprātīgie: #{@event.registered_volunteers} / #{@event.necessary_volunteers}
        
      div.border-l-2.pl-2.w-full.border-scout-blue
        p
          =@event.description

app/views/events/_event_table.html.slim
table.table-auto.w-full id="dataTable"
  thead.bg-scout-blue.text-white
    tr
      th.px-6.py-3.text-start Nosaukums
      th.px-6.py-3.text-start Datums
      th.px-6.py-3.text-start Brīvprātīgie
      th.px-6.py-3.text-start Dalībnieki
      th.px-6.py-3.no-sort

  tbody
    - @events.each do |event|
      tr.border-b
        td.px-6.py-3
          = event.name
        td.px-6.py-3
          ="#{event.date_from.strftime("%d.%m")}#{event.date_to ? "-" + event.date_to.strftime("%d.%m") : ""}"
        td.px-6.py-3
          | #{event.registered_volunteers} / #{ event.necessary_volunteers }
        td.px-6.py-3
          | #{event.registered_participants} / #{ event.max_participants }
        td.px-6.py-3
          =link_to edit_event_path(event), class: "block w-5"
            =image_tag 'icons/edit.svg', size:"30"

app/views/events/_invite_table.html.slim
table.table-auto.w-full id="dataTable2"
  thead.bg-scout-blue.text-white
    tr
      th.px-6.py-3.text-start Nosaukums 
      th.px-6.py-3.text-start Datums
      th.px-6.py-3.text-start Brīvprātīgie 
      th.px-6.py-3.text-start Dalībnieki
      th.px-6.py-3.no-sort

  tbody
    - @invites.each do |invite|
      tr.border-b
        td.px-6.py-3 
          = invite.name
        td.px-6.py-3 
          ="#{invite.date_from.strftime("%d.%m")}#{invite.date_to ? "-" + invite.date_to.strftime("%d.%m") : ""}"
        td.px-6.py-3 
          | #{invite.registered_volunteers} / #{ invite.necessary_volunteers }
        td.px-6.py-3 
          | #{invite.registered_participants} / #{ invite.max_participants }
        td.px-6.py-3 
          =link_to show_unit_event_path(invite), class: "block w-5"
              =image_tag 'icons/show.svg', size:"30"

app/views/events/edit.html.slim
.flex.flex-col.justify-start.p-5.w-full.lg:w-4/5.lg:h-full.lg:p-10
  h1.title-normal
    |Labot pasākuma datus 
  .flex.flex-col-reverse.w-full.h-full.lg:flex-row
    .flex.flex-col.lg:w-1/2 
      =render "event_form"
      =button_to "Dzēst pasākumu", event_path(@event.id), method: :delete, form: {data: {turbo_confirm: 'Vai esat drošs?'}}, class: "btn-secondary border-scout-red text-scout-red text-sm min-h-[18px] lg:text-lg"
    .flex.mb-10.lg:w-1/2.flex-col.lg:ml-10.lg:mb-0
      .flex.flex-col.w-full.border-2.border-scout-blue.p-4.overflow-auto class="max-h-[400px] lg:max-h-[80vh] rounded-[30px]"
        =form_for @invite do |f|
          .flex.flex-col.items-center.place-content-between.w-full.lg:flex-row
            .flex.flex-col
              = f.select :unit, options_for_select(@units), {}, class: "input-field-blue ml-0 pr-10 w-full lg:w-fit"
              = f.label :unit, "Vienība", class: "input-label-static"
            .flex.flex-col
              = f.select :rank, options_for_select(ranks_short), {}, class: "input-field-blue lg:ml-[-40px] w-full lg:w-fit"
              = f.label :unit, "Pakāpe", class: "input-label-static lg:ml-[-40px] "
            = f.hidden_field :event, value: @event.id
            = f.submit "Ielūgt", class: "btn-secondary w-full lg:w-fit mb-5"
        table
          -@invites.each do |invite|
            tr.flex.items-center.place-content-between
              td.ml-2
                =invite.unit.full_name
              td.text-end 
                =invite.rank
              td
                =button_to "#{agent_mobile? ? "X" : "Dzēst"}", invite_path(invite.id), method: :delete, class: "btn-secondary border-scout-red text-scout-red text-sm min-h-[18px] lg:text-lg"
      p.input-label-static.mb-1 
        |Uz pasākumu ir ielūgti

app/views/events/index.html.slim
.flex.flex-col.justify-start.p-5.w-full.lg:w-4/5.lg:h-full.lg:p-10
  .flex.flex-col.w-full.h-full.lg:flex-row
    .max-h-1/3.h-fit.lg:w-1/2.overflow-y-auto
      .flex.justify-between.items-center
        h1.title-normal 
          = @mode == "unit" ? "Vienības rīkotie pasākumi" : "Organizācijas rīkotie pasākumi"
        =link_to "+Pasākums" ,new_event_path, class:  @current_user.unit.unit_active? ? 'btn-primary ' : "btn-primary disabled-link"
      .border-2.rounded-xl.overflow-y-auto
        =render "event_table"
    .max-h-1/3.h-fit.mt-10.lg:w-1/2.lg:ml-10.lg:mt-0
      h1.title-normal
        = @mode == "unit" ? "Vienības tuvākie pasākumi" : "Organizācijas tuvākie pasākumi"
      .border-2.rounded-xl.overflow-y-auto
        =render "invite_table"

app/views/events/new.html.slim
.flex.flex-col.justify-start.p-5.w-full.lg:w-4/5.lg:h-full.lg:p-10
  .flex.w-full.h-full.flex-col
    h1.title-normal
      |Jauns pasākums 
    =render "create_event_form"

app/views/events/show.html.slim
.flex.flex-col.justify-start.p-5.w-full.lg:w-4/5.lg:h-full.lg:p-10.lg:flex-row
  .flex.flex-col.w-full
    =render "event_show"
    =button_tag "< Atgriezties", onClick: "history.go(-1);", class: "btn-primary w-fit mt-20"
  .flex.flex-col.mt-10.lg:w-1/3.lg:ml-10.lg:mt-0
    h1.title-normal.text-center.text-xl
      | Pieteikties
    -if !current_user_registered_for(@event.id).present? && Date.today < @event.registration_till
      =form_for @event_registration do |f|
        div.border-2.rounded-xl.p-2.flex.flex-col
          =f.select :role,  options_for_select(registration_positions(@event.id)), {}, class: "input-field-blue"
          =f.label :role, "Piesakos kā:", class: "input-label-static"
          .
            =f.text_area :position, class: "input-field-blue h-60 peer rounded-[30px]", placeholder: ""
            =f.label :position, "Komentāri:", class: "input-label"
          =f.hidden_field :event_id, value: @event.id
          -if current_user.personal_information.present?
            div
              = check_box_tag 'agreed_to_personal_info', :private_info_permission, true,  class: 'border-2 border-scout-blue rounded-sm ml-2'
              = label_tag "agreed_to_personal_info", :private_info_permission, class: 'text-sm font-bold text-scout-blue ml-2'
                  |Iesniegt aptaujas lapu
          p.text-sm.text-scout-red.m-2.font-bold
            |Ja Jums nav iesniegta aptaujas lapa, lūdzam to sagatavot rakstiskā formā uz nometni.
          =f.submit "Pieteikties", class: "btn-primary"
    -elsif !current_user_registered_for(@event.id).present? 
      div.border-2.rounded-3xl.text-center.border-scout-blue.py-1.px-2.w-fit.mb-5
        p.font-bold
          | Pieteikšanās uz šo pasākumu beigusies
    -else
      div.flex.flex-col.items-center.w-fit
        div.border-2.rounded-3xl.text-center.border-scout-blue.py-1.px-2.w-fit.mb-5
          p.font-bold
            | Jūs esat pieteicies kā #{current_user_registered_for(@event.id).role}
        p.text-sm.text-scout-red.font-bold.text-center
          | Ja vēlaties atsaukt savu dalību, lūdzu sazinieties ar savu vienības priekšnieku.

app/views/events/show_unit.html.slim
.flex.flex-col.justify-start.p-5.w-full.lg:w-4/5.h-full.lg:p-10.lg:flex-row
  .flex.flex-col.w-full
    =render "event_show"
    =link_to "< Atgriezties", events_path, class: "btn-primary w-fit mt-10"
  .flex.flex-col.lg:w-1/3.lg:ml-10.lg:items-end 
    div.flex.flex-col.items-center.w-fit
      =link_to "Reģistrējušies dalībnieki", event_registration_path(@event), class: "btn-primary"