config/routes.rb
Rails.application.routes.draw do
  #Aplikācijas sesijas ceļi
  post "/session", to: "session#create"
  delete "/session", to: "session#destroy"

  #Lietotāja daļas ceļi
  get ":password/aktivizet", to: "session#first_login", as: "aktivizet"
  get ":password/atjaunot", to: "session#password_reset", as: "atjaunot"

  get "/profils", to: "users#profile"
  post "lietotajs/:id/atjaunot_paroli", to: "users#password_update"
  resources :users, path: :lietotajs do
    member do
      post "unit_update"
      post "password_update"
      post "send_password_reset"
      post "resignation"
      post "empower_user"
      post "depower_user"
    end
    collection do
      post "promise"
      get "solijuma_registracija", to: "users#bulk_promise"
    end
  end

  #Aptaujas lapas ceļi. Neizmantojam resources, jo aptaujas lapa ir piesaistīta katram lietotājam
  get "/aptaujas_lapa", to: "personal_information#show"
  delete "/aptaujas_lapa", to: "personal_information#destroy"
  get "/aptaujas_lapa/iesniegt", to: "personal_information#new"
  post "/aptaujas_lapa/iesniegt", to: "personal_information#create"
  patch "/aptaujas_lapa/iesniegt", to: "personal_information#update"
  get "/aptaujas_lapa/labot", to: "personal_information#edit"
  get "/aptaujas_lapa/skatit", to: "personal_information#display"

  #Vienības darbības sfēras ceļi
  resources :units, path: :vieniba do
    member do
      patch "undestory"
    end
  end
  resources :positions, only: ["create", "destroy"]
  resources :weekly_activities, only: ["create", "destroy"]
  resources :membership_fee_payments, path: :biedra_naudas_maksajumi, only: ["create", "destroy"] do
    member do
      get "maksajumi", to: "membership_fee_payments#list"
    end
    collection do
      get "registret_maksajumus", to: "membership_fee_payments#bulk_payment"
      get "maksajumu_vesture", to: "membership_fee_payments#user_payment_history"
    end
  end

  #Atskaišu ceļi
  get "/biedru_atskaites", to: "reports#member_report"
  get "/vienibas_atskaites", to: "reports#unit_report"

  #Pasākumu ceļi
  resources :events, path: :pasakums do
    member do
      get "show_unit"
    end
  end
  resources :invites, only: ["create", "destroy"]
  resources :event_registrations, only: ["create", "destroy", "show"], path: "pieteikumi"

  #Lapa kurā nav vajadzīga reģistrācija
  root "static#landing"
end

app/models/unit.rb
class Unit < ApplicationRecord
  #Definējam obligātos laukus
  validates :city, :number, :legal_adress, :bank_account, presence: true

  #Objektu saistības
  belongs_to :unit_leader, class_name: "User", optional: true

  has_many :users, foreign_key: 'unit_id'
  has_many :events
  has_many :invites
  has_many :event_invites, through: :invites, source: :event
  has_many :membership_fee_payments
  has_many :positions
  has_many :weekly_activities

  def full_name #Vienības pilnais nosaukums
    if number == 0 
      "LSGCO"
    elsif city.ends_with?("i")
      "#{city.slice(0...-1)}u #{number}. vienība"
    elsif city.ends_with?("ls")
      "#{city} #{number}. vienība"
    elsif city.ends_with?("s")
      "#{city.slice(0...-1)}a #{number}. vienība"
    else
      "#{city}s #{number}. vienība"
    end
  end

  def get_actual_events(user) #Pasākumi, kuriem vienībai ir ielūgumi norādītajai pakāpei
    events = invites.includes(:event).future.where(rank: user.rank).map(&:event).select { |event| event.publishable }

    if(user.volunteer == true)
      volunteer_events = invites.includes(:event).future.where("necessary_volunteers >= registered_volunteers").map(&:event).select { |event| 
      event.publishable && 
      event.volunteer_scope == "Ielūgtās vienības" || 
      event.volunteer_scope == "Vienība" && event.unit == user.unit}

      events.concat(volunteer_events)
    end

    return events
  end

  def unit_active? #Vai vienība ir dzēsta
    !deleted_at.present?
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  #Pārbauda vai lietotājs ir autorizējies un vai tam ir pieteikamas piekļuves, vai ir vienības biedrs vai valde
  before_action :authorized?, :unit_access?, :unit_member?
  #Izveidot apskatīt un dzēst var tikai valdes pārstāvis
  before_action :org_access?, only: ["create", "index", "new", "destroy"]

  def new #Jauns vienības objekts ar noklusēto vērtību ar ko aizpildīt jaunas vienības formu
    session[:current_tab] = "new_unit"  #Iestatam, ka izvēlnes aktīvā sekcija ir jaunas vienības pievienošana
    @unit = Unit.new()
    @unit.membership_fee = 0
    @users = User.where(activity_statuss: "Vadītājs").map { |user| [user.full_name, user.id] } #Vienību priekšnieku kandidāti
  end

  def index #Visas sistēmas vienības
    session[:current_tab] = "unit_list"
    @units = Unit.all
  end

  def show #Vienibas dati
    session[:current_tab] = "unit" unless session[:current_tab] == "unit_list" #Iestatam, ka izvēlnes aktīvā sekcija ir vienības apskate
    @unit = Unit.find(params[:id])
    @weekly_activities = @unit.weekly_activities.all.order(day: :asc)
    @members = @unit.users.where.not(activity_statuss: "Izstājies") #Aktīvie biedri
    @unit_leader = @unit.unit_leader

    if @unit.number == 0
      render 'org_edit'
    end
  end

  def create #Izveido jaunu vienību
    @leader = User.find(params[:leader_id])
    @unit = Unit.new(unit_create_params)
    @unit.membership_fee = 0 #Noklusējumā 0 dalības maksa

    #Saglabā jauno vienību un atjauno vienības priekšnieka piekļuves līmeni, paziņo
    if @unit.save! && @leader.update(permission_level: "pklv_vaditajs", unit: @unit) && @leader.activity_statuss == "Vadītājs"
      redirect_to unit_path(@unit), notice: "Jauna vienība izveidota"
    else
      redirect_to root_path, alert: "Kļūda"
    end
  end

  def edit #Vienības objekts ar ko aizpildīt vienības datu atjaunošanas formu
    @unit = Unit.find(params[:id])
    @weekly_activities = @unit.weekly_activities.all.order(day: :asc)
    @new_activity = WeeklyActivity.new #Tukšs iknedēļas nodarbības objekts
    @leader_candidates = @unit.users.where("activity_statuss = ? OR id = ?", 3, current_user.id).map { |user| [user.full_name, user.id] } #Vienības priekšnieku kandindāti un esošie priekšnieki
  end

  def update #Vienības datu atjaunošana
    @unit = Unit.find(params[:id])
    @leader = params[:leader_id] ? User.find(params[:leader_id]) : @unit.unit_leader #Norādītais priekšnieks
    
     membership_fee = unit_update_params[:membership_fee].present? ? unit_update_params[:membership_fee] : 0  #Vienmēr jābūt dalības maksai

    if @leader != @unit.unit_leader #Ja priekšnieks mainīts, atjauno priekšnieku un tā piekļuves, un noņem vecā priekšnieka piekļuves
      if !@unit.unit_leader.pklv_valde?
        @unit.unit_leader.update(permission_level: "pklv_biedrs")
      end

      @unit.unit_leader = @leader
      
      if !@leader.pklv_valde? #Ja valdes loceklis, nevajag mainīt piekļuves
        @leader.update(permission_level: "pklv_vaditajs")
      end
    end

    if @unit.update(unit_update_params.merge(membership_fee: membership_fee)) #Saglabājam vienības datus ar dalības maksu, ja kļūda Paziņo
      unless @unit.number == 0 
         redirect_to unit_path(@unit), notice: "Vienības infromācija atjaunota"
         return
      end
      redirect_to units_path, notice: "Organizācijas informācija atjaunota"
    else
      redirect_to root_path, alert: "Kļūda"
    end
  end

  def destroy #Nestingrā dzēšana, ja neizdodas reģistrēt dzēšanas datumu Paziņo kļūdu
    @unit = Unit.find(params[:id])
    if @unit.update(deleted_at: Date.today)
      redirect_to unit_path(@unit), notice: "Vienības atzīmēta kā neaktīva"
    else
      redirect_to root_path, alert: "Kļūda"
    end
  end

  def undestory #Nestingrās dzēšanas atgriešana, ja neizdodas dzēst dzēšanas datumu Paziņo kļūdu
    @unit = Unit.find(params[:id])
    if @unit.update(deleted_at: nil)
      redirect_to unit_path(@unit), notice: "Vienības atzīmēta kā aktīva"
    else
      redirect_to root_path, alert: "Kļūda"
    end
  end

  protected

  #Pieņem vienības objektu, kas aizpildīts atļautajiem laukiem. Šo izmanto taisot jaunu vienību.
  def unit_create_params
    params.require(:unit).permit(:city, :number, :legal_adress, :bank_account)
  end

  #Pieņem vienības objektu, kas aizpildīts atļautajiem laukiem. Šo izmanto atjaunojot vienību.
  def unit_update_params
    params.require(:unit).permit(:legal_adress, :activity_location_name, :email, :phone, :bank_account, :comments, :membership_fee, :leader_id)
  end

  #Palīgfunkcija, kas pārbauda vai lietotājs ir vienības biedrs vai valdes pārstāvis
  def unit_member?
    redirect_to root_path, alert: "Nav atļauts" unless current_user.unit.id == params[:id].to_i || current_user.pklv_valde?
  end
end

app/views/units/_bulk_action_buttons.html.slim
.flex.flex-col
  =link_to "Reģistrēt maksājumus", registret_maksajumus_membership_fee_payments_path(), class: "btn-primary"
  =link_to "Reģistrēt solījumus", solijuma_registracija_users_path(), class: "btn-primary"

app/views/units/_unit_data.html.slim
div.flex.flex-col.divide-y-2.h-full
  -if @unit.deleted_at.present?
    div.lg:flex.gap-2
      h1.subtitle.text-scout-red
        |!!!Vienība neaktīva!!!
  div
    div.lg:flex.gap-2
      h1.subtitle
        |Nosaukums:
      p.paragraph-normal
        =@unit.full_name
    div.lg:flex.gap-2
      h1.subtitle
        |Juridiskā adrese:
      p.paragraph-normal
        =@unit.legal_adress
    div.lg:flex.gap-2
      h1.subtitle
        |Epasts:
      p.paragraph-normal
        =@unit.email.present? ? @unit.email : "#{@unit_leader.present? && @unit_leader.email.present? ? @unit_leader.email : "-"} (vienības priekšnieka epasts)"
    div.lg:flex.gap-2
      h1.subtitle
        |Telefons:
      p.paragraph-normal
        =@unit.phone.present? ? @unit.phone : "#{@unit_leader.present? && @unit_leader.phone.present? ? @unit_leader.phone : "-"} (vienības priekšnieka telefons)"
  div.pt-5.pb-5
    div.lg:flex.gap-2
      h1.subtitle
        |Bankas konts:
      p.paragraph-normal
        =@unit.bank_account
    .lg:flex.gap-2
      h1.subtitle
        |Dalības maksa:
      p.paragraph-normal
        =@unit.membership_fee.to_s + "€"
  -if @unit.comments.present?
    div.pt-5.pb-5
      .flex.flex-col
        h1.subtitle
          |Publiskie komentāri:
        p.paragraph-normal.max-h-44.overflow-auto.text-sm
          =@unit.comments
  div.pt-5.pb-5
    div.lg:flex.gap-2
      h1.subtitle
        |Nodarbību vieta:
      p.paragraph-normal
        =@unit.activity_location_name
    div.flex.flex-col
      h1.subtitle
        |Nodarbību grafiks:
      -if @weekly_activities.present?
        table.w-full.border-spacing-y-72
          - @weekly_activities.each do |activity|
            tr
              td =activity.day
              td =activity.time.strftime("%H:%M")
              td =activity.rank
      -else
        p.paragraph-normal
          |Nav norādīts nodarbību grafiks

app/views/units/_unit_member_table.html.slim
table.table-auto.w-full id="dataTable"
  thead.bg-scout-blue.text-white
    tr
      th.px-6.py-3.text-start Vārds 
      th.px-6.py-3.text-start Uzvārds
      th.px-6.py-3.text-start Pakāpe
      th.px-6.py-3.text-start Statuss
      th.px-6.py-3.no-sort

  tbody
    - @members.each do |member|
      tr.border-b
        td.px-6.py-3 
          = member.name
        td.px-6.py-3 
          = member.surname
        td.px-6.py-3 
          | #{member.rank} #{ member.promise? ? (member.sex == "F" ? "☘️" : "⚜️") : "" }
        td.px-6.py-3 
          = member.activity_statuss
        td.px-6.py-3 
          =link_to user_path(member), class: "block w-5"
            =image_tag 'icons/edit.svg', size:"30"
      

app/views/units/_unit_table.html.slim
table.table-auto.w-full id="dataTable"
  thead.bg-scout-blue.text-white
    tr
      th.px-6.py-3.text-start Nosaukums 
      th.px-6.py-3.text-start Priekšnieks
      th.px-6.py-3.text-start Statuss
      th.px-6.py-3.no-sort

  tbody
    - @units.each do |unit|
      tr.border-b
        td.px-6.py-3 
          = unit.full_name
        td.px-6.py-3 
          = unit.unit_leader ? "#{unit.unit_leader.name} #{unit.unit_leader.surname}" : "-"
        td.px-6.py-3 
          = unit.unit_active? ? "Aktīva" : "Neaktīva kopš #{unit.deleted_at}"
        td.px-6.py-3 
          =link_to unit_path(unit), class: "block w-5"
            =image_tag 'icons/edit.svg', size:"30"
      

app/views/units/edit.html.slim
flex.flex-col.justify-start.p-5.w-full.lg:w-4/5.lg:h-full.lg:p-10
  div
    h1.title-normal
      =@unit.full_name
    p.paragraph-normal
      |Atjauno vienības datus
  .flex.flex-col.mt-5.w-full
    = form_for @unit do |f|
      div.flex.flex-col.w-full.mb-10.lg:flex-row.lg:mb-10
        .flex.flex-col.content-around.h-2/3.lg:w-1/2
          .
            = f.text_field :legal_adress, class: 'input-field-blue w-full peer', required: true, placeholder: ""
            = f.label :legal_adress, 'Juridiskā adrese', class: 'input-label'
          .
            = f.text_field :activity_location_name, class: 'input-field-blue w-full peer', placeholder: ""
            = f.label :activity_location_name, 'Nodarbību notikšanas vieta', class: 'input-label'
          .
            = f.text_area :comments, class: 'input-field-blue w-full h-60 overflow-auto rounded-[30px] peer', placeholder: ""
            = f.label :comments, 'Publiskie komentāri', class: 'input-label'
          
          
        .flex.flex-col.content-around.h-2/3.lg:w-1/2.lg:ml-10
          .
            = f.email_field :email, class: 'input-field-blue w-full peer', placeholder: ""
            = f.label :email, "Epasts #{!@unit.email.present? ? "(ja atstāts tukš tiek lietots vienības priekšnieka epasts)" : ""}", class: 'input-label'
          .
            = f.phone_field :phone, class: 'input-field-blue w-full peer', placeholder: ""
            = f.label :phone, "Telefona numurs #{!@unit.phone.present? ? "(ja atstāts tukš tiek lietots vienības priekšnieka telefona numurs)" : ""}", class: 'input-label'
          .
            = f.text_field :bank_account, class: 'input-field-blue w-full peer', required: true, placeholder: ""
            = f.label :bank_account, 'Bankas konts', class: 'input-label'
          .
            = f.number_field :membership_fee, class: 'input-field-blue w-full peer', placeholder: ""
            = f.label :membership_fee, 'Biedra nauda (vienības)', class: 'input-label'
          .
            = select_tag :leader_id, options_for_select(@leader_candidates, @unit.unit_leader ? @unit.unit_leader.id : 0), class: 'input-field-blue w-full', required: true
            = label_tag :leader_id, "Vienības priekšnieks", class: "input-label-static"
          = f.submit "Atjaunot vienības datus", class: "btn-primary w-full"
    
  .w-full.flex.flex-col.lg:flex-row
    .lg:w-1/2
      h1.title-normal.text-lg
        |Nodarbību grafiks
      -if @weekly_activities.present?
        div class="lg:max-h-[190px] overflow-auto"
          table.w-full.border-spacing-y-40
            -@weekly_activities.each do |activity|
              tr
                td.text-start =activity.day
                td.text-center =activity.time.strftime("%H:%M")
                td.text-center =agent_mobile? ? activity.rank.gsub("/", "/\n") : activity.rank
                td.text-end =button_to "#{agent_mobile? ? "X" : "Dzēst"}", weekly_activity_path(activity), method: :delete, class: "btn-secondary border-scout-red text-scout-red text-sm min-h-[18px] lg:text-lg"
      -else
        p.paragraph-normal
          |Nav norādīts nodarbību grafiks          
      
    .flex.flex-col.mt-6.w-full.lg:w-1/2.lg:ml-10
      = form_for @new_activity do |f|
        .flex.flex-col.items-center.w-full
          .flex.flex-col.w-full.lg:flex-row
            = f.select :day,  options_for_select(["Pirmdiena", "Otrdiena", "Trešdiena", "Ceturtdiena", "Piektdiena", "Sestdiena", "Svētdiena"]), {}, class: "input-field-blue w-full lg:w-1/2"
            = f.time_field :time, required: true, class: "input-field-blue w-full lg:w-1/2"
            = f.select :rank,  options_for_select(ranks_full), {}, class: "input-field-blue w-full lg:w-1/2"
          = f.submit "Pievienot nodarbību", class: "btn-secondary self-center text-end lg:self-end"

app/views/units/index.html.slim
flex.flex-col.justify-start.p-5.w-full.lg:w-4/5.lg:h-full.lg:p-10
  .flex.flex-col.w-full.h-full.lg:flex-row
    .max-h-1/3.h-fit.w-full
      .flex.flex-col.justify-between.lg:flex-row
        h1.title-normal 
          |Organizācijas vienības
        div.w-full
          input.input-field-blue.w-full.peer type="text" id="searchField" placeholder=""
          label.input-label
                |Meklēt

      .border-2.rounded-xl.overflow-y-auto.mt-5
        =render "unit_table"

app/views/units/new.html.slim
flex.flex-col.justify-start.p-5.w-full.lg:w-4/5.lg:h-full.lg:p-10
  div
    h1.title-normal
      | Jauna vienība
  .flex.flex-col.mt-10.w-full
    = form_for @unit, url: units_path, method: :post do |f|
      div.flex.flex-col.w-full.mb-10.lg:flex-row.lg:mb-20
        .flex.flex-col.content-around.h-2/3.lg:w-1/2
          .
            = f.text_field :city, class: 'input-field-blue w-full peer', required: true, placeholder: ""
            = f.label :city, 'Pilsēta', class: 'input-label'
          .
            = f.number_field :number, class: 'input-field-blue peer', required: true, placeholder: ""
            = f.label :number, 'Cipars', class: 'input-label'
          .
            = f.text_field :legal_adress, class: 'input-field-blue w-full peer', required: true, placeholder: ""
            = f.label :legal_adress, 'Juridiskā adrese', class: 'input-label'
          .  
            = f.text_field :bank_account, class: 'input-field-blue w-full peer', required: true, placeholder: ""
            = f.label :bank_account, 'Bankas konts', class: 'input-label'
          .
            = select_tag :leader_id, options_for_select(@users), class: 'input-field-blue w-full', required: true
            = f.label :leader_id, "Vienības priekšnieks", class: 'input-label-static'
          = f.submit "Izveidot vienību", class: 'btn-primary w-full'

app/views/units/org_edit.html.slim
flex.flex-col.justify-start.p-5.w-full.lg:w-4/5.lg:h-full.lg:p-10
  .flex.flex-col.w-full.h-full.lg:flex-row
    .max-h-1/3.h-fit.lg:w-full
      .flex.flex-col.justify-between.lg:flex-row
        h1.title-normal 
          |Organizācijas iestatījumi
      = form_for @unit do |f|
        div.flex.flex-col.w-full.mb-10.lg:flex-row.lg:mt-20
          .flex.flex-col.content-around.h-2/3.lg:w-1/2
            .
              = f.text_field :legal_adress, class: 'input-field-blue w-full peer', required: true, placeholder: ""
              = f.label :legal_adress, 'Juridiskā adrese', class: 'input-label'
            .
              = f.number_field :membership_fee, class: 'input-field-blue w-full peer', placeholder: ""
              = f.label :membership_fee, 'Biedra nauda (organizāciajs)', class: 'input-label'
            .
              = f.email_field :email, class: 'input-field-blue w-full peer', placeholder: ""
              = f.label :email, "Epasts #{!@unit.email.present? ? "(ja atstāts tukš tiek lietots vienības priekšnieka epasts)" : ""}", class: 'input-label'
            .
              = f.phone_field :phone, class: 'input-field-blue w-full peer', placeholder: ""
              = f.label :phone, "Telefona numurs #{!@unit.phone.present? ? "(ja atstāts tukš tiek lietots vienības priekšnieka telefona numurs)" : ""}", class: 'input-label'
            .
              = f.text_field :bank_account, class: 'input-field-blue w-full peer', required: true, placeholder: ""
              = f.label :bank_account, 'Bankas konts', class: 'input-label'
            = f.submit "Atjaunot organizācijas datus", class: "btn-primary w-full"

           
           
         
      

app/views/units/show.html.slim
flex.flex-col.justify-start.p-5.w-full.lg:w-4/5.lg:h-full.lg:p-10
  .flex.flex-col.w-full.h-full.lg:flex-row
    .max-h-1/3.h-fit.lg:w-2/5
      .flex.flex-col.justify-between.lg:flex-row
        h1.title-normal 
          |Vienības dati
        -if @current_user == @unit.unit_leader
          =link_to "Labot datus" ,edit_unit_path(@unit), class:"btn-ternary ml-0 p-0"
        -if @current_user.pklv_valde?
          -if @unit.unit_active?
            =button_to "Atzīmēt kā neaktīvu", unit_path(@unit), method: :delete, class: "btn-secondary border-scout-red text-scout-red text-sm min-h-[18px] lg:text-lg"
          -else
            =button_to "Aktivizēt vienību", undestory_unit_path(@unit), method: :patch, class: "btn-secondary border-scout-blue text-scout-blue text-sm min-h-[18px] lg:text-lg"
      .border-2.rounded-xl.p-4.overflow-y-auto
        =render "unit_data" 
      =render "bulk_action_buttons"
    .max-h-1/3.h-fit.mt-5.lg:ml-10.lg-mt-0.lg:w-3/4
      h1.title-normal
        |Vienības biedri
      .border-2.rounded-xl.overflow-y-auto
        =render "unit_member_table"