config/routes.rb
Rails.application.routes.draw do
  #Aplikācijas sesijas ceļi
  post "/session", to: "session#create"
  delete "/session", to: "session#destroy"

  #Lietotāja daļas ceļi
  get ":password/aktivizet", to: "session#first_login", as: "aktivizet"
  get ":password/atjaunot", to: "session#password_reset", as: "atjaunot"

  get "/profils", to: "users#profile"
  post "lietotajs/:id/atjaunot_paroli", to: "users#password_update"
  resources :users, path: :lietotajs do
    member do
      post "unit_update"
      post "password_update"
      post "send_password_reset"
      post "resignation"
      post "empower_user"
      post "depower_user"
    end
    collection do
      post "promise"
      get "solijuma_registracija", to: "users#bulk_promise"
    end
  end

  #Aptaujas lapas ceļi. Neizmantojam resources, jo aptaujas lapa ir piesaistīta katram lietotājam
  get "/aptaujas_lapa", to: "personal_information#show"
  delete "/aptaujas_lapa", to: "personal_information#destroy"
  get "/aptaujas_lapa/iesniegt", to: "personal_information#new"
  post "/aptaujas_lapa/iesniegt", to: "personal_information#create"
  patch "/aptaujas_lapa/iesniegt", to: "personal_information#update"
  get "/aptaujas_lapa/labot", to: "personal_information#edit"
  get "/aptaujas_lapa/skatit", to: "personal_information#display"

  #Vienības darbības sfēras ceļi
  resources :units, path: :vieniba do
    member do
      patch "undestory"
    end
  end
  resources :positions, only: ["create", "destroy"]
  resources :weekly_activities, only: ["create", "destroy"]
  resources :membership_fee_payments, path: :biedra_naudas_maksajumi, only: ["create", "destroy"] do
    member do
      get "maksajumi", to: "membership_fee_payments#list"
    end
    collection do
      get "registret_maksajumus", to: "membership_fee_payments#bulk_payment"
      get "maksajumu_vesture", to: "membership_fee_payments#user_payment_history"
    end
  end

  #Atskaišu ceļi
  get "/biedru_atskaites", to: "reports#member_report"
  get "/vienibas_atskaites", to: "reports#unit_report"

  #Pasākumu ceļi
  resources :events, path: :pasakums do
    member do
      get "show_unit"
    end
  end
  resources :invites, only: ["create", "destroy"]
  resources :event_registrations, only: ["create", "destroy", "show"], path: "pieteikumi"

  #Lapa kurā nav vajadzīga reģistrācija
  root "static#landing"
end

app/views/layouts/_dropdown_menu.html.slim
div.border-2.flex.flex-col.px-5 x-data="{menuOpen: false}"
  div.flex.justify-between.items-center
    = image_tag  "LSGCO_logo_full.svg", class:"h-32 text-center p-4"
    button(x-on:click="menuOpen = !menuOpen")
      =image_tag src="icons/burger_menu.svg", size: "30px", id: "dropdown-button"
  
  div (x-show="menuOpen" x-transition)
    -if @user_permission_level == "login"
      =form_tag session_path do
        .flex.flex-col
          div.group
            input.input-field-blue.peer type="text" name="username" placeholder=""
            label.input-label
              |Lietotājs
          div
            input.input-field-blue.peer type="password" name="password" placeholder=""
            label.input-label
              |Parole
          button.btn-primary.flex.items-center.justify-between.my-3 type="submit" 
            |Pievienoties
            =image_tag 'icons/login.svg', size:"30"
    -else
      .flex.flex-col.divide-y-2.divide-scout-gold 
        -if @user_permission_level == "pklv_valde" || @user_permission_level == "pklv_vaditajs"
          div 
            -if @user_permission_level == "pklv_valde"
              =link_to biedru_atskaites_path, class: current_tab == "member_report" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
                |Biedru atskaite
                =image_tag 'icons/report.svg', size:"30"
            =link_to current_user.pklv_valde? ? vienibas_atskaites_path() : vienibas_atskaites_path(id: current_user.unit), class: current_tab == "unit_report" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
                |Vienības atskaite
                =image_tag 'icons/report.svg', size:"30"
        -if @user_permission_level == "pklv_valde"
          div 
            =link_to new_unit_path, class: current_tab == "new_unit" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
              |Pievienot vienību
              =image_tag 'icons/new_unit.svg', size:"30"
            =link_to units_path, class: current_tab == "unit_list" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
              |Vienības
              =image_tag 'icons/units.svg', size:"30"
            -if @current_user != @current_user.unit.unit_leader
              =link_to new_user_path, class: current_tab == "new_member" ? "btn-active flex items-center justify-between my-3" : current_user.unit.unit_active? ? "btn-primary flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3 disabled-link"
                |Pievienot biedru
                =image_tag 'icons/new_user.svg', size:"30"
              
        -if @user_permission_level == "pklv_vaditajs" ||  @user_permission_level == "pklv_valde" && @current_user.activity_statuss == "Vadītājs"
            div
              =link_to new_user_path, class: current_tab == "new_member" ? "btn-active flex items-center justify-between my-3" : current_user.unit.unit_active? ? "btn-primary flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3 disabled-link"
                |Pievienot biedru
                =image_tag 'icons/new_user.svg', size:"30"
              =link_to events_path, class: current_tab == "events" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
                |Pasākumi
                =image_tag 'icons/events.svg', size:"30"
              =link_to unit_path(current_user.unit), class: current_tab == "unit" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
                |Mana vienība 
                =image_tag 'icons/unit.svg', size:"30"
        -if @user_permission_level == "pklv_biedrs" || @user_permission_level == "pklv_vaditajs" || @user_permission_level == "pklv_valde"
          div
            =link_to maksajumu_vesture_membership_fee_payments_path, class: current_tab == "payments" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
              |Maksājumi 
              =image_tag 'icons/money.svg', size:"30"
            =link_to aptaujas_lapa_path, class: current_tab == "private_info" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
              |Aptaujas lapa 
              =image_tag 'icons/private_information.svg', size:"30"
            =link_to profils_path, class: current_tab == "profile" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
              |Mans profils
              =image_tag 'icons/current_user.svg', size:"30"
            =link_to session_path, data: { turbo_method: "delete" }, class: "btn-primary flex items-center justify-between my-3"
              |Izrakstīties
              =image_tag 'icons/logout.svg', size:"30"

app/views/layouts/_popup_notices.html.slim
div (x-data="{ show: true }" x-init="setTimeout(() => show = false, 3000)" x-show="show" x-transition
  class="#{agent_mobile? ? "sticky top-0 right-0" : "absolute bottom-5 right-10"}")
  -if notice
    div.border-scout-gold.border-t-8.bg-scout-blue.rounded-b.text-white.px-4.py-3.shadow-md[id="popup"]
      .flex
        div.px-3.py-1
          img src= asset_path("icons/info.svg")
        div.text-lg.pr-3
          = notice
  -elsif alert
    div.border-scout-red.border-t-8.bg-scout-blue.rounded-b.text-white.px-4.py-3.shadow-md[id="popup"]
      .flex
        div.px-3.py-1
          img src= asset_path("icons/alert.svg")
        div.text-lg.pr-3
          = alert

app/views/layouts/_sidebar.html.slim
.h-screen.border-r-4.w-1/5.p-2.flex.flex-col.justify-between
  = image_tag  "LSGCO_logo.png" 

  -if @sidebar_state == "login"
    =form_tag session_path do
      .flex.flex-col
        label.input-label
          |Lietotājs
        input.input-field-blue type="text" name="username"
        label.input-label
          |Parole
        input.input-field-blue type="password" name="password"
        button.btn-primary.flex.items-center.justify-between.my-3 type="submit" 
          |Pievienoties
          =image_tag 'icons/login.svg', size:"30"
  -else
    .flex.flex-col.divide-y-2.divide-scout-gold 
      -if @sidebar_state == "pklv_vaditajs"
          div
            =link_to new_user_path, class: current_tab == "new_member" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
              |Pievienot biedru
              =image_tag 'icons/new_user.svg', size:"30"
            =link_to events_path, class: current_tab == "events" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
              |Pasākumi
              =image_tag 'icons/events.svg', size:"30"
            =link_to unit_path(current_user.unit), class: current_tab == "unit" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
              |Mana vienība 
              =image_tag 'icons/unit.svg', size:"30"
      -if @sidebar_state == "pklv_biedrs" || @sidebar_state == "pklv_vaditajs" || @sidebar_state == "pklv_valde"
        div
          =link_to aptaujas_lapa_path, class: current_tab == "private_info" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
            |Aptaujas lapa 
            =image_tag 'icons/private_information.svg', size:"30"
          =link_to profils_path, class: current_tab == "profile" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
            |Mans profils
            =image_tag 'icons/current_user.svg', size:"30"
          =link_to session_path, class: "btn-primary flex items-center justify-between my-3"
            |Izrakstīties
            =image_tag 'icons/logout.svg', size:"30"
      

app/views/layouts/_sidebar_menu.html.slim
.h-screen.border-r-4.w-1/4.p-2.flex.flex-col.justify-between.sticky.top-0
  = image_tag  "LSGCO_logo_full.svg", class: "p-4"

  -if @user_permission_level == "login"
    =form_tag session_path do
      .flex.flex-col.w-full
        div.group
          input.input-field-blue.peer type="text" name="username" placeholder=""
          label.input-label
            |Lietotājs
        div
          input.input-field-blue.peer type="password" name="password" placeholder=""
          label.input-label
            |Parole
        button.btn-primary.justify-between.my-3 type="submit" 
          |Pievienoties
          =image_tag 'icons/login.svg', size:"30"
  -else
    .flex.flex-col.divide-y-2.divide-scout-gold 
      -if @user_permission_level == "pklv_valde" || @user_permission_level == "pklv_vaditajs"
        div 
          -if @user_permission_level == "pklv_valde"
            =link_to biedru_atskaites_path, class: current_tab == "member_report" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
              |Biedru atskaite
              =image_tag 'icons/report.svg', size:"30"
          =link_to current_user.pklv_valde? ? vienibas_atskaites_path() : vienibas_atskaites_path(id: current_user.unit), class: current_tab == "unit_report" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
              |Vienības atskaite
              =image_tag 'icons/report.svg', size:"30"
      -if @user_permission_level == "pklv_valde"
        div 
          =link_to new_unit_path, class: current_tab == "new_unit" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
            |Pievienot vienību
            =image_tag 'icons/new_unit.svg', size:"30"
          =link_to units_path, class: current_tab == "unit_list" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
            |Vienības
            =image_tag 'icons/units.svg', size:"30"
          -if @current_user != @current_user.unit.unit_leader
            =link_to new_user_path, class: current_tab == "new_member" ? "btn-active flex items-center justify-between my-3" : current_user.unit.unit_active? ? "btn-primary flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3 disabled-link"
              |Pievienot biedru
              =image_tag 'icons/new_user.svg', size:"30"
        
      -if @user_permission_level == "pklv_vaditajs" ||  @user_permission_level == "pklv_valde" && @current_user == @current_user.unit.unit_leader
          div
            =link_to new_user_path, class: current_tab == "new_member" ? "btn-active flex items-center justify-between my-3" : current_user.unit.unit_active? ? "btn-primary flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3 disabled-link"
              |Pievienot biedru
              =image_tag 'icons/new_user.svg', size:"30"
            =link_to events_path, class: current_tab == "events" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
              |Pasākumi
              =image_tag 'icons/events.svg', size:"30"
            =link_to unit_path(current_user.unit), class: current_tab == "unit" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
              |Mana vienība 
              =image_tag 'icons/unit.svg', size:"30"
      -if @user_permission_level == "pklv_biedrs" || @user_permission_level == "pklv_vaditajs" || @user_permission_level == "pklv_valde"
        div
          =link_to maksajumu_vesture_membership_fee_payments_path, class: current_tab == "payments" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
            |Maksājumi 
            =image_tag 'icons/money.svg', size:"30"
          =link_to aptaujas_lapa_path, class: current_tab == "private_info" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
            |Aptaujas lapa 
            =image_tag 'icons/private_information.svg', size:"30"
          =link_to profils_path, class: current_tab == "profile" ? "btn-active flex items-center justify-between my-3" : "btn-primary flex items-center justify-between my-3"
            |Mans profils
            =image_tag 'icons/current_user.svg', size:"30"
          =link_to session_path, data: { turbo_method: "delete" }, class: "btn-primary flex items-center justify-between my-3"
            |Izrakstīties
            =image_tag 'icons/logout.svg', size:"30"
      

app/views/layouts/application.html.slim
doctype html

html
  head
    title LSGCOIs
    meta name="viewport" content="width=device-width, initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags  "application"
    = favicon_link_tag asset_path('LSGCO_logo_small.svg')

  body class="#{agent_mobile? ? "flex flex-col" : "flex"}"
    = render partial: "layouts/popup_notices"
    -if agent_mobile?
      = render partial: "layouts/dropdown_menu" 
    -else  
      = render partial: "layouts/sidebar_menu" 
    = yield